'use client';
import { CheckCircle2, Pause, Play, Save } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';

interface Provider { baseUrl:string|null; model:string|null; timeoutSeconds:number; chunkCharacters:number; automaticPaused:boolean; hasApiKey:boolean }
interface Source { sourceId:string; enabled:boolean; requestIntervalMs:number; lastError:string|null; lastCheckedAt:number|null }
interface Health { heartbeatAt:number|null; healthy:boolean }
interface Novel { id:string; displayTitle:string; autoTranslate:boolean; autoCheck:boolean }
type Tab='General'|'Provider'|'Sources'|'Automation'|'Reader';
function isProvider(value:unknown):value is Provider{return !!value&&typeof value==='object'&&'timeoutSeconds' in value&&'automaticPaused' in value;}
function isSources(value:unknown):value is Source[]{return Array.isArray(value)&&value.every(item=>!!item&&typeof item==='object'&&'sourceId' in item);}
function isHealth(value:unknown):value is Health{return !!value&&typeof value==='object'&&'healthy' in value;}
function isNovels(value:unknown):value is Novel[]{return Array.isArray(value)&&value.every(item=>!!item&&typeof item==='object'&&'displayTitle' in item);}

export function SettingsClient(){
  const [tab,setTab]=useState<Tab>('General');const [provider,setProvider]=useState<Provider|null>(null);const [sources,setSources]=useState<Source[]>([]);const [health,setHealth]=useState<Health|null>(null);const [novels,setNovels]=useState<Novel[]>([]);const [apiKey,setApiKey]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const [fontSize,setFontSize]=useState(20);const [lineHeight,setLineHeight]=useState(1.85);const [theme,setTheme]=useState('light');
  const load=useCallback(async()=>{const responses=await Promise.all([fetch('/api/settings/provider',{cache:'no-store'}),fetch('/api/sources',{cache:'no-store'}),fetch('/api/health',{cache:'no-store'}),fetch('/api/novels',{cache:'no-store'})]);const values:unknown[]=await Promise.all(responses.map(response=>response.json()));if(responses[0]?.ok&&isProvider(values[0]))setProvider(values[0]);if(responses[1]?.ok&&isSources(values[1]))setSources(values[1]);if(responses[2]?.ok&&isHealth(values[2]))setHealth(values[2]);if(responses[3]?.ok&&isNovels(values[3]))setNovels(values[3]);},[]);
  useEffect(()=>{void load();setFontSize(Number(localStorage.getItem('reader-font-size'))||20);setLineHeight(Number(localStorage.getItem('reader-line-height'))||1.85);setTheme(localStorage.getItem('reader-theme')??'light');},[load]);
  async function saveProvider(event:React.FormEvent){event.preventDefault();if(!provider)return;setError('');const response=await fetch('/api/settings/provider',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({baseUrl:provider.baseUrl,model:provider.model,timeoutSeconds:provider.timeoutSeconds,chunkCharacters:provider.chunkCharacters,...(apiKey?{apiKey}:{})})});const value:unknown=await response.json();if(response.ok&&isProvider(value)){setProvider(value);setApiKey('');setMessage('Provider settings saved.');}else setError('Save failed');}
  async function testProvider(){const response=await fetch('/api/settings/provider/test',{method:'POST'});setMessage(response.ok?'Provider test queued. See Activity for the result.':'');setError(response.ok?'':'Provider test failed');}
  async function pause(){if(!provider)return;const response=await fetch('/api/settings/automation',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({paused:!provider.automaticPaused})});const value:unknown=await response.json();if(response.ok&&isProvider(value))setProvider(value);}
  async function updateSource(source:Source,changes:{enabled?:boolean;requestIntervalMs?:number}){const response=await fetch(`/api/sources/${source.sourceId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(changes)});const value:unknown=await response.json();const updatedList=[value];if(response.ok&&isSources(updatedList)){const updated=updatedList[0]!;setSources(items=>items.map(item=>item.sourceId===updated.sourceId?updated:item));}else setError('Source update failed');}
  async function testSource(sourceId:string){const response=await fetch(`/api/sources/${sourceId}/check`,{method:'POST'});setMessage(response.ok?`${sourceId} test queued.`:'');setError(response.ok?'':'Source test failed');}
  async function updateNovel(novel:Novel,changes:{autoTranslate?:boolean;autoCheck?:boolean}){const response=await fetch(`/api/novels/${novel.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(changes)});if(response.ok)void load();else setError('Novel automation update failed');}
  function saveReader(){localStorage.setItem('reader-font-size',String(fontSize));localStorage.setItem('reader-line-height',String(lineHeight));localStorage.setItem('reader-theme',theme);setMessage('Reader defaults saved in this browser.');}
  if(!provider)return <div className="empty">Loading settings…</div>;
  const tabs:Tab[]=['General','Provider','Sources','Automation','Reader'];
  return <><section className="hero"><div><div className="eyebrow">Configuration</div><h1>Settings</h1><p className="muted">Credentials stay encrypted at rest and never return to the browser.</p></div></section><div className="segmented" style={{width:'fit-content',marginBottom:22}}>{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</div>
    {message&&<div className="notice" style={{marginBottom:16}}>{message}</div>}{error&&<div className="error" style={{marginBottom:16}}>{error}</div>}
    {tab==='General'&&<section className="panel"><h2>Worker</h2><p><i className={`status-dot ${health?.healthy?'ready':''}`}/> {health?.healthy?'Healthy':'No recent heartbeat'}</p><div className="muted">{health?.heartbeatAt?`Last heartbeat ${new Date(health.heartbeatAt).toLocaleString()}`:'Start the worker process to handle imports and translations.'}</div></section>}
    {tab==='Provider'&&<form className="panel stack" onSubmit={saveProvider}><h2>Translation provider</h2><div className="form-grid"><label className="field">OpenAI-compatible base URL<input className="input" type="url" required value={provider.baseUrl??''} onChange={event=>setProvider({...provider,baseUrl:event.target.value})}/></label><label className="field">Model<input className="input" required value={provider.model??''} onChange={event=>setProvider({...provider,model:event.target.value})}/></label><label className="field">API key<input className="input" type="password" placeholder={provider.hasApiKey?'Stored — enter to replace':'Required'} value={apiKey} onChange={event=>setApiKey(event.target.value)}/></label><label className="field">Timeout (seconds)<input className="input" type="number" min="30" max="600" value={provider.timeoutSeconds} onChange={event=>setProvider({...provider,timeoutSeconds:Number(event.target.value)})}/></label><label className="field">Chunk characters<input className="input" type="number" min="500" max="6000" value={provider.chunkCharacters} onChange={event=>setProvider({...provider,chunkCharacters:Number(event.target.value)})}/></label></div><div className="toolbar"><button className="btn primary" type="submit"><Save size={16}/> Save provider</button><button className="btn" type="button" onClick={()=>void testProvider()}><CheckCircle2 size={16}/> Test provider</button></div></form>}
    {tab==='Sources'&&<section className="panel"><h2>Sources</h2>{sources.map(source=><div className="toggle" key={source.sourceId}><div><strong>{source.sourceId}</strong><div className="muted">{source.lastError??(source.lastCheckedAt?`Checked ${new Date(source.lastCheckedAt).toLocaleString()}`:'Not checked yet')}</div><input className="input" style={{width:150,marginTop:8}} type="number" min="2000" step="500" value={source.requestIntervalMs} onChange={event=>void updateSource(source,{requestIntervalMs:Number(event.target.value)})}/></div><div className="toolbar"><button className="btn" onClick={()=>void testSource(source.sourceId)}>Test</button><button className={`switch ${source.enabled?'on':''}`} aria-label={`Toggle ${source.sourceId}`} onClick={()=>void updateSource(source,{enabled:!source.enabled})}/></div></div>)}</section>}
    {tab==='Automation'&&<div className="stack"><button className="btn" style={{width:'fit-content'}} onClick={()=>void pause()}>{provider.automaticPaused?<><Play size={16}/> Resume all automatic jobs</>:<><Pause size={16}/> Pause all automatic jobs</>}</button>{novels.map(novel=><section className="panel" key={novel.id}><strong>{novel.displayTitle}</strong><div className="toggle"><span>Automatic translation</span><button className={`switch ${novel.autoTranslate?'on':''}`} aria-label={`Toggle translation for ${novel.displayTitle}`} onClick={()=>void updateNovel(novel,{autoTranslate:!novel.autoTranslate})}/></div><div className="toggle"><span>Automatic update checks</span><button className={`switch ${novel.autoCheck?'on':''}`} aria-label={`Toggle checks for ${novel.displayTitle}`} onClick={()=>void updateNovel(novel,{autoCheck:!novel.autoCheck})}/></div></section>)}</div>}
    {tab==='Reader'&&<section className="panel stack"><h2>Reader defaults</h2><div className="form-grid"><label className="field">Font size<input className="input" type="number" min="16" max="28" value={fontSize} onChange={event=>setFontSize(Number(event.target.value))}/></label><label className="field">Line height<select className="select" value={lineHeight} onChange={event=>setLineHeight(Number(event.target.value))}><option value="1.65">Compact</option><option value="1.85">Comfortable</option><option value="2.05">Spacious</option></select></label><label className="field">Theme<select className="select" value={theme} onChange={event=>setTheme(event.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></label></div><button className="btn primary" style={{width:'fit-content'}} onClick={saveReader}><Save size={16}/> Save reader defaults</button></section>}
  </>;
}
