PRAGMA foreign_keys = ON;
CREATE TABLE novels (id TEXT PRIMARY KEY, source_id TEXT NOT NULL, source_novel_id TEXT NOT NULL, title TEXT NOT NULL, custom_title TEXT, description TEXT, author TEXT, index_url TEXT NOT NULL, start_chapter_url TEXT NOT NULL, start_ordinal INTEGER NOT NULL, include_start INTEGER NOT NULL, auto_translate INTEGER NOT NULL DEFAULT 0, auto_check INTEGER NOT NULL DEFAULT 0, next_check_at INTEGER, last_checked_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE UNIQUE INDEX novels_source_identity ON novels(source_id, source_novel_id);
CREATE TABLE novel_covers (novel_id TEXT PRIMARY KEY REFERENCES novels(id) ON DELETE CASCADE, image BLOB NOT NULL, content_hash TEXT NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE chapters (id TEXT PRIMARY KEY, novel_id TEXT NOT NULL REFERENCES novels(id) ON DELETE CASCADE, source_chapter_id TEXT NOT NULL, canonical_url TEXT NOT NULL, ordinal INTEGER NOT NULL, title TEXT NOT NULL, paragraphs TEXT, source_hash TEXT, fetched_at INTEGER, read_at INTEGER, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE UNIQUE INDEX chapters_novel_source ON chapters(novel_id, source_chapter_id);
CREATE UNIQUE INDEX chapters_canonical_url ON chapters(canonical_url);
CREATE INDEX chapters_novel_ordinal ON chapters(novel_id, ordinal);
CREATE TABLE reading_progress (novel_id TEXT PRIMARY KEY REFERENCES novels(id) ON DELETE CASCADE, current_chapter_id TEXT REFERENCES chapters(id) ON DELETE SET NULL, source_scroll_ratio REAL NOT NULL DEFAULT 0 CHECK(source_scroll_ratio BETWEEN 0 AND 1), english_scroll_ratio REAL NOT NULL DEFAULT 0 CHECK(english_scroll_ratio BETWEEN 0 AND 1), updated_at INTEGER NOT NULL);
CREATE TABLE translations (chapter_id TEXT PRIMARY KEY REFERENCES chapters(id) ON DELETE CASCADE, target TEXT NOT NULL DEFAULT 'en', paragraphs TEXT NOT NULL, source_hash TEXT NOT NULL, model TEXT NOT NULL, base_url TEXT NOT NULL, prompt_version INTEGER NOT NULL, completed_at INTEGER NOT NULL, input_tokens INTEGER, output_tokens INTEGER);
CREATE TABLE translation_runs (id TEXT PRIMARY KEY, chapter_id TEXT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE, model TEXT NOT NULL, base_url TEXT NOT NULL, provider_revision INTEGER NOT NULL, source_hash TEXT NOT NULL, prompt_version INTEGER NOT NULL, status TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE translation_chunks (run_id TEXT NOT NULL REFERENCES translation_runs(id) ON DELETE CASCADE, chunk_index INTEGER NOT NULL, input TEXT NOT NULL, output TEXT, input_tokens INTEGER, output_tokens INTEGER);
CREATE UNIQUE INDEX translation_chunks_run_index ON translation_chunks(run_id, chunk_index);
CREATE TABLE source_settings (source_id TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 1, request_interval_ms INTEGER NOT NULL DEFAULT 2000 CHECK(request_interval_ms >= 2000), next_request_at INTEGER NOT NULL DEFAULT 0, last_error TEXT, last_checked_at INTEGER);
CREATE TABLE provider_settings (id INTEGER PRIMARY KEY DEFAULT 1 CHECK(id = 1), base_url TEXT, model TEXT, encrypted_api_key TEXT, revision INTEGER NOT NULL DEFAULT 1, timeout_seconds INTEGER NOT NULL DEFAULT 120 CHECK(timeout_seconds BETWEEN 30 AND 600), chunk_characters INTEGER NOT NULL DEFAULT 10000 CHECK(chunk_characters BETWEEN 500 AND 15000), automatic_paused INTEGER NOT NULL DEFAULT 0);
CREATE TABLE jobs (id TEXT PRIMARY KEY, kind TEXT NOT NULL, payload TEXT NOT NULL, dedupe_key TEXT, status TEXT NOT NULL DEFAULT 'queued', origin TEXT NOT NULL DEFAULT 'manual', attempt INTEGER NOT NULL DEFAULT 0, run_after INTEGER NOT NULL, lease_token TEXT, lease_expires_at INTEGER, progress TEXT, error TEXT, parent_job_id TEXT REFERENCES jobs(id) ON DELETE SET NULL, novel_id TEXT REFERENCES novels(id) ON DELETE CASCADE, chapter_id TEXT REFERENCES chapters(id) ON DELETE CASCADE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX jobs_status_run_after ON jobs(status, run_after);
CREATE INDEX jobs_parent ON jobs(parent_job_id);
CREATE INDEX jobs_novel ON jobs(novel_id);
CREATE UNIQUE INDEX jobs_active_dedupe ON jobs(dedupe_key) WHERE dedupe_key IS NOT NULL AND status IN ('queued','running');
CREATE TABLE worker_state (id INTEGER PRIMARY KEY DEFAULT 1 CHECK(id = 1), heartbeat_at INTEGER NOT NULL);
INSERT INTO provider_settings(id) VALUES (1);
INSERT INTO source_settings(source_id) VALUES ('piaotia');
